version: "3"
services:
  document-merge-service:
    build:
      context: .
      args:
        REQUIREMENTS: requirements-dev.txt
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000",
      ]
    environment:
      - ENV=dev
