# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("template", models.FileField(max_length=1024, upload_to="")),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            (
                                "docx-template",
                                "Docx Template engine (https://github.com/elapouya/python-docx-template)",
                            )
                        ],
                        max_length=20,
                    ),
                ),
            ],
        )
    ]
